export const POPULATE_PRODUCTS = "POPULATE_PRODUCTS";
export const POPULATE_PRODUCT_DETAILS = "POPULATE_PRODUCT_DETAILS";

export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const SAVE_REVIEW = "SAVE_REVIEW";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const CHECKOUT = "CHECKOUT";
export const POPULATE_PRODUCT_REJECTED = "POPULATE_PRODUCT_REJECTED";
export const SAVE_PRODUCT_REJECTED = "SAVE_PRODUCT_REJECTED";
export const DELETE_PRODUCT_REJECTED = "DELETE_PRODUCT_REJECTED";
